### ISSUE TITLE
Bounty - Defillama Adapter - $1000 USD

### ISSUE THREAD

**Issue by sg-meter** [meterio/Meter-Bounty-Program#1]
## Objective

Create an adapter for https://defillama.com/ for the Meter Chain

## Context

The Meter ecosystem is poised for growth. We are looking to gain exposure to broader DeFI users through integration with defillama. 

## Reference

https://docs.llama.fi/list-your-project/submit-a-project

## Acceptance Criteria
* [x] Create and test the adapter
* [x] Submit and Merge the PR 

## Reward
$1000 USD paid in MTRG tokens upon delivery

**Comment by Dirt-Nasty** [comment]
I've created the adapter and put in a PR here: https://github.com/DefiLlama/DefiLlama-Adapters/pull/1318

**Comment by sg-meter** [comment]
Integration completed.
